apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhooker
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: $aws_role_arn
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhooker
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhooker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhooker
subjects:
- kind: ServiceAccount
  name: webhooker
  namespace: argocd
- kind: ServiceAccount
  name: webhooker
  namespace: argocd
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhooker-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhooker
subjects:
- kind: Group
  name: monitoring
  namespace: argocd